# Generated by Django 4.1 on 2023-07-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.SmallAutoField(db_column='CustomerId', editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=30)),
                ('last_name', models.CharField(db_column='LastName', max_length=30)),
                ('phone_number', models.CharField(db_column='PhoneNumber', max_length=50)),
                ('land_size', models.IntegerField(blank=True, db_column='LandSize', null=True)),
                ('ownership', models.CharField(blank=True, db_column='Ownership', max_length=50, null=True)),
                ('land_owner', models.CharField(blank=True, db_column='LandOwner', max_length=50, null=True)),
                ('land_owner_phone', models.CharField(blank=True, db_column='LandOwnerPhone', max_length=50, null=True)),
                ('land_upi', models.CharField(blank=True, db_column='LandUPI', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, db_column='BankName', max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, db_column='BankAccount', max_length=50, null=True)),
                ('bank_account_name', models.CharField(blank=True, db_column='BankAccountName', max_length=50, null=True)),
                ('harvest_balance', models.IntegerField(blank=True, db_column='TotalHarvest', null=True)),
                ('input_balance', models.IntegerField(blank=True, db_column='TotalInput', null=True)),
            ],
            options={
                'db_table': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('pivot_id', models.SmallAutoField(db_column='PivotId', editable=False, primary_key=True, serialize=False)),
                ('pivot_head', models.CharField(db_column='PivotHead', max_length=50)),
                ('pivot_name', models.CharField(db_column='PivotName', max_length=50)),
                ('pivot_location', models.CharField(db_column='PivotLocation', max_length=50)),
                ('pivot_phone', models.CharField(db_column='PivotPhone', max_length=50)),
                ('pivot_email', models.CharField(db_column='PivotEmail', max_length=50)),
            ],
            options={
                'db_table': 'Pivot',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('input_id', models.SmallAutoField(db_column='InputId', editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('item', models.CharField(db_column='Item', max_length=50)),
                ('description', models.CharField(db_column='Description', max_length=100)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unit_price', models.IntegerField(db_column='UnitPrice')),
                ('total_value', models.IntegerField(db_column='TotalValue')),
                ('payment_mode', models.CharField(db_column='PaymentMode', max_length=50)),
                ('farmer_id', models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, to='Pivots.farmer')),
                ('pivot_id', models.ForeignKey(db_column='PivotId', on_delete=django.db.models.deletion.CASCADE, to='Pivots.pivot')),
            ],
            options={
                'db_table': 'Inputs',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.SmallAutoField(db_column='HarvestId', editable=False, primary_key=True, serialize=False)),
                ('crop', models.CharField(db_column='Crop', max_length=50)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unit_price', models.IntegerField(db_column='UnitPrice')),
                ('total_value', models.IntegerField(db_column='TotalValue')),
                ('date', models.DateField(db_column='Date')),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=100, null=True)),
                ('farmer_id', models.ForeignKey(db_column='FarmerId', on_delete=django.db.models.deletion.CASCADE, to='Pivots.farmer')),
                ('pivot_id', models.ForeignKey(db_column='PivotId', on_delete=django.db.models.deletion.CASCADE, to='Pivots.pivot')),
            ],
            options={
                'db_table': 'Harvests',
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='pivot_id',
            field=models.ForeignKey(db_column='PivotId', on_delete=django.db.models.deletion.CASCADE, to='Pivots.pivot'),
        ),
    ]
